### ISSUE TITLE
missing word in cabal description

### ISSUE THREAD

**Issue by juhp** [josefs/STMonadTrans#1]
The .cabal says

> The reason is that the [???] will be duplicated across the different answers and this cause Bad Things to happen (such as loss of referential transparency).

There seems to be a missing word "[???]" in the above sentence and it is not immediately obvious what it is.

**Comment by juhp** [comment]
Also "this causes" would probably be better.

**Comment by josefs** [comment]
Thanks for pointing out the problems. Should be fixed now.
