### ISSUE TITLE
runST is broken

### ISSUE THREAD

**Issue by ajscholl** [josefs/STMonadTrans#3]
This program produces bad core and a wrong result:

```
module Main where

import Control.Monad
import Control.Monad.Trans
import Control.Monad.ST.Trans

import Data.Array

foo :: Int -> Maybe (Array Int Int)
foo i = runSTArray $ do
    arr <- newSTArray (1, 3) 0
    lift $ guard $ i > 0
    writeSTArray arr 2 i
    return arr

ups :: (Maybe (Array Int Int, Array Int Int))
ups = (,) <$> foo 5 <*> foo 6

main :: IO ()
main = print ups
```

Core for ups:

```
ups1 :: Int
ups1 = I# 6

ups2 :: Int
ups2 = I# 5

ups :: Maybe (Array Int Int, Array Int Int)
ups =
  case newArray# 3 foo3 realWorld# of _ { (# ipv, ipv1 #) ->
  case writeArray# ipv1 1 ups2 ipv of s2# { __DEFAULT ->
  case unsafeFreezeArray# ipv1 s2# of _ { (# ipv2, ipv3 #) ->
  case writeArray# ipv1 1 ups1 ipv of s2#1 { __DEFAULT ->
  case unsafeFreezeArray# ipv1 s2#1 of _ { (# ipv4, ipv5 #) ->
  Just (Array foo2 foo1 3 ipv3, Array foo2 foo1 3 ipv5)
  }
  }
  }
  }
  }
```

Note that only one array is ever created!

Result:
Just (array (1,3) [(1,0),(2,6),(3,0)],array (1,3) [(1,0),(2,6),(3,0)])

Problem:

runST can be inlined. Now two different ST operations are started with the same state token (realWorld#) and GHC is free to eliminate duplicate expressions, float them out and do other things with them. See also the comments in http://hackage.haskell.org/package/base-4.8.2.0/docs/src/GHC.ST.html#runST, as the ST monad has the same problem. A NOINLINE pragma on runST could help.

**Comment by zilberstein** [comment]
I've been seeing similar problems. In code like this:

```
runST $ do
  foo <- newSTRef Nothing
  bar <- newSTRef Nothing
  ...
```

`foo` gets some garbage `Just` value even though it's never updated. If I modify it slightly so that the `newSTRef` is not the first statement in the `do` block:

```
runST $ do
  return ()
  foo <- newSTRef Nothing
  bar <- newSTRef Nothing
  ...
```

It works as expected

**Comment by andrewthad** [comment]
This issue causes problems for me too. I've defined my own `noInlineRunSTT` wrapper around the `runST` provided by this library. It would be nice to see this actually be in the library itself though.

**Comment by josefs** [comment]
Sorry for taking so long to react on this issue. I've uploaded a new version of the library to Hackage which has a {-# NOINLINE runST #-}.
@ajscholl , thanks for the excellent test case. I've added it to the repo.
